version: '3.1'

services:
  web:
    container_name: nginx
    image: project.nginx
    depends_on:
      - phpfpm
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/sites-enabled/default"
      - "./docker/etc/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf"
      - "./docker/etc/example.local.crt:/etc/ssl/certs/example.local.crt"
      - "./docker/etc/example.local.key:/etc/ssl/private/example.local.key"
      - "./:/var/www/html"
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    build:
      context: ./docker
      dockerfile: ./Dockerfile.nginx
    networks:
      - local

  phpfpm:
    container_name: phpfpm
    image: project.phpfpm
    depends_on:
      - composer
      - tests
    restart: always
    volumes:
      - "./docker/etc/php-fpm/www.conf:/etc/php/7.3/fpm/pool.d/www.conf"
      - "./:/var/www/html"
    build:
      context: ./docker
      dockerfile: ./Dockerfile.phpfpm
    networks:
      - local

  composer:
    container_name: composer
    image: project.composer
    volumes:
      - "./:/app"
      - project-tmp:/var/project/tmp
    build:
      context: ./docker
      dockerfile: ./Dockerfile.composer

  tests:
    container_name: tests
    image: project.tests
    depends_on:
      - composer
    volumes:
      - "./:/app"
      - project-tmp:/var/project/tmp
    build:
      context: ./docker
      dockerfile: ./Dockerfile.tests

networks:
  local:

volumes:
  project-tmp: