version: '3.1'

services:
  nginx:
    container_name: nginx
    image: project.nginx
    depends_on:
      - phpfpm
    volumes:
      - "./docker/nginx/conf/default.conf:/etc/nginx/sites-enabled/default"
      - "./docker/nginx/conf/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf"
      - "./docker/nginx/conf/example.local.crt:/etc/ssl/certs/example.local.crt"
      - "./docker/nginx/conf/example.local.key:/etc/ssl/private/example.local.key"
      - "./:/var/www/html"
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    build: ./docker/nginx
    networks:
      - local

  phpfpm:
    container_name: phpfpm
    image: project.phpfpm
    depends_on:
      - composer
      - tests
    restart: always
    volumes:
      - "./docker/phpfpm/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf"
      - "./:/var/www/html"
    build: ./docker/phpfpm
    networks:
      - local

  composer:
    container_name: composer
    image: project.composer
    volumes:
      - "./:/app"
      - project-tmp:/var/project/tmp
    build: ./docker/composer

  tests:
    container_name: tests
    image: project.tests
    depends_on:
      - composer
    volumes:
      - "./:/app"
      - project-tmp:/var/project/tmp
    build: ./docker/tests

networks:
  local:

volumes:
  project-tmp:
